-- =========================================
-- 7TPclan shared Tryout Server database
-- Run this in Supabase SQL Editor.
-- =========================================

create table if not exists public.tryout_servers (
  id bigint generated by default as identity primary key,
  name text not null,
  link text not null default '',
  available boolean not null default false,
  active boolean not null default false,
  hosted_by text,
  updated_at timestamptz not null default now()
);

alter table public.tryout_servers enable row level security;

-- Public visitors can read server cards.
drop policy if exists "Public can view tryout servers"
on public.tryout_servers;

create policy "Public can view tryout servers"
on public.tryout_servers
for select
to anon, authenticated
using (true);

-- Authenticated staff can manage rows.
-- IMPORTANT:
-- Only create staff auth accounts for people you trust.
-- This prototype uses Supabase Auth accounts as the staff login.
drop policy if exists "Authenticated staff can insert tryout servers"
on public.tryout_servers;

create policy "Authenticated staff can insert tryout servers"
on public.tryout_servers
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated staff can update tryout servers"
on public.tryout_servers;

create policy "Authenticated staff can update tryout servers"
on public.tryout_servers
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated staff can delete tryout servers"
on public.tryout_servers;

create policy "Authenticated staff can delete tryout servers"
on public.tryout_servers
for delete
to authenticated
using (true);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tryout_servers_updated_at
on public.tryout_servers;

create trigger tryout_servers_updated_at
before update on public.tryout_servers
for each row
execute function public.set_updated_at();

-- Optional: create your first server.
insert into public.tryout_servers
  (name, link, available, active, hosted_by)
values
  ('Tryout Server 1', '', false, false, null)
on conflict do nothing;
